name: Deploy docker image to Cloud Run
'on':
    push:
        branches:
            - main

jobs:
    build_and_deploy:
    -   name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
            project_id: ${{ secrets.GCP_PROJECT_ID }}
            service_account_key: ${{ secrets.GCP_SA_KEY }}
            export_default_credentials: true
    -   name: Use gcloud CLI
        run: gcloud info