name: Deploy docker image to Cloud Run
'on':
    push:
        branches:
            - main

# https://github.com/google-github-actions/setup-gcloud/blob/master/example-workflows/cloud-run/README.md
jobs:
    build_and_deploy:
        steps:
            -   name: Set up Cloud SDK
                uses: google-github-actions/setup-gcloud@master
                with:
                    project_id: ${{ secrets.GCP_PROJECT_ID }}
                    service_account_key: ${{ secrets.GCP_SA_KEY }}
                    export_default_credentials: true
            -   name: Build image
                run: gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/pdf-generator-backend
            -   name: Deploy to Cloud Run
                run: gcloud run deploy --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/pdf-generator-backend --platform managed